/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
    1,2,3,5,8,13,21,34,55,89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int fibonacci(int nth_index);

int main()
{
    long total = 0;
    int n = 0;

    int fib_counter = fibonacci(n);
    while(fib_counter < 4000000)
    {
        if(fib_counter % 2 == 0)
        {
            total += fib_counter;
        }
        fib_counter = fibonacci(n++);
    }

    cout << "total = " << total << '\n';

    return 0;
}

int fibonacci(int nth_index) {
    if(nth_index == 0 || nth_index == 1)
    {
        return nth_index;
    } 

    return fibonacci(nth_index-1) + fibonacci(nth_index-2);
}